In [3]:
import numpy as np
from math import cos,sin
# 假设的vec向量和target目标点坐标
v_x, v_y = 3, 4
x, y = 10, 5

# 计算旋转角度（负值，因为我们是要将坐标系旋转到与vec一致，即相反方向）
theta = -np.arctan2(v_y, v_x)

# 构建旋转矩阵
rot_matrix = [
    [cos(theta), -sin(theta)],
    [sin(theta), cos(theta)]
]

# 应用旋转矩阵变换目标点
x_rotated, y_rotated = np.dot(rot_matrix, [x, y])

x_rotated, y_rotated


(10.0, -4.999999999999999)

In [2]:
import torch
import torch.nn.functional as F

# 假设 input 是一个形状为 [1, 3, 24, 24] 的张量，代表一批中只有一张 24x24 的 RGB 图像
input = torch.randn(1, 3, 24, 24)

# 将图像的高度和宽度分别增加到 48x48
# 将图像的大小增加两倍
output = F.interpolate(input, scale_factor=2, mode='bilinear', align_corners=False)
# output = F.interpolate(input, size=(48, 48), mode='bilinear', align_corners=False)
print(output.shape)

torch.Size([1, 3, 48, 48])


In [2]:
import torch

# 创建一个一维张量
x = torch.tensor([1, 2, 4, 7, 11])

# 计算一阶差分
dx = torch.diff(x)

print(dx)

dx = torch.diff(x, n = 2)

print(dx)


tensor([1, 2, 3, 4])
tensor([1, 1, 1])


In [19]:
import torch
a = torch.arange(8*20*2).view(8,20,2)
b = torch.arange(8*20*1).view(8,20,1)
torch.cat([a,b], dim=2).shape
torch.cat()

torch.Size([8, 20, 3])

In [3]:
from shapely.geometry import LineString
import math
import numpy as np
# 创建一个 LineString 对象
line = LineString([(0, 0), (2, 2), (6, 6)])

# 在 LineString 上根据指定距离插值
point_at_distance = line.interpolate(4.5)

print(point_at_distance)
np.linalg.norm((3.1820,3.1820),ord=2)

POINT (3.181980515339464 3.181980515339464)


4.500027555471188

In [4]:
import pandas as pd
df = pd.read_csv('/data/wangchen/dataset/argo/val/data/1.csv')
df.groupby(['TRACK_ID', 'OBJECT_TYPE']).groups

{('00000000-0000-0000-0000-000000000000', 'AV'): [0, 8, 16, 25, 36, 48, 59, 71, 85, 100, 115, 131, 146, 161, 174, 187, 201, 215, 229, 244, 259, 273, 285, 296, 305, 314, 322, 329, 335, 341, 346, 352, 358, 366, 375, 385, 394, 401, 407, 412, 418, 424, 431, 437, 443, 449, 453, 457, 462, 466], ('00000000-0000-0000-0000-000000189446', 'OTHERS'): [7, 14, 17, 26, 37, 49, 60, 72, 86, 101, 116, 132, 147, 162, 175, 188, 202, 216, 230, 245, 260, 274, 286, 297, 306, 315, 323, 332, 336, 343, 347, 353, 362, 369, 379, 390, 397, 402, 408, 413, 419, 425, 432, 438, 444, 450, 454, 458, 464, 468], ('00000000-0000-0000-0000-000000189649', 'OTHERS'): [1, 9, 18, 27, 38, 50, 61, 73, 87, 102, 117, 137, 152, 167, 186, 200, 203, 217, 231, 246, 261, 275, 287, 298, 307, 316, 324, 333, 338, 342, 348, 354, 359, 367, 376, 386, 395, 403], ('00000000-0000-0000-0000-000000189661', 'AGENT'): [4, 15, 19, 28, 39, 51, 62, 74, 88, 103, 118, 133, 148, 163, 185, 199, 204, 218, 232, 247, 262, 276, 288, 299, 308, 317, 325, 330, 3

### 经过preprocess之后的feature pkl结构

In [1]:
import pickle
with open("/data/wangchen/SIMPL/data_argo/features/val/1.pkl", 'rb') as f:
    data = pickle.load(f)
    print(type(data))
    

<class 'pandas.core.frame.DataFrame'>


In [2]:
data

SEQ_ID CITY_NAME                   ORIG  \
0       1       PIT  [1774.185, 390.52426]   

                                               ROT  \
0  [[0.763196, -0.6461671], [0.6461671, 0.763196]]   

                                           TIMESTAMP  \
0  [0.0, 0.10130906, 0.2013238, 0.30182153, 0.404...   

                                               TRAJS  \
0  [[[-10.531179, 0.0], [-9.919388, -0.009070396]...   

                                          TRAJS_CTRS  \
0  [[0.0, 0.0], [3.5342479, 5.774828], [35.09165,...   

                                          TRAJS_VECS  \
0  [[1.0, 0.0], [-0.9999814, 0.006099099], [-0.99...   

                                           PAD_FLAGS  \
0  [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...   

                                          LANE_GRAPH  
0  {'node_ctrs': [[[-6.4954567 -1.571598 ], [-5.1...

In [3]:
data.loc[0,'ROT']

array([[ 0.763196 , -0.6461671],
       [ 0.6461671,  0.763196 ]], dtype=float32)

In [4]:
data.loc[0,'TIMESTAMP']

array([0.        , 0.10130906, 0.2013238 , 0.30182153, 0.404795  ,
       0.50286627, 0.6027162 , 0.70522726, 0.8068577 , 0.9042282 ,
       1.0040736 , 1.1045349 , 1.2087593 , 1.3070736 , 1.4046686 ,
       1.5037879 , 1.6074322 , 1.701994  , 1.8037946 , 1.9046421 ,
       1.9997149 , 2.1024604 , 2.1974428 , 2.3007045 , 2.3987706 ,
       2.4967506 , 2.5984778 , 2.6977046 , 2.7991128 , 2.8962455 ,
       2.9967537 , 3.0976777 , 3.1959357 , 3.2967925 , 3.3963404 ,
       3.4933097 , 3.6000366 , 3.6982973 , 3.795776  , 3.9012353 ,
       4.0016856 , 4.0989585 , 4.1939073 , 4.296197  , 4.3989387 ,
       4.4984493 , 4.5971093 , 4.696355  , 4.8004627 , 4.897036  ],
      dtype=float32)

In [17]:
data.loc[0,'TRAJS'][4,:,:]


array([[-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-7.5461608e-01, -5.1105076e-10],
       [-9.9777108e-01, -2.5467498e-03],
       [ 2.6405776e-01,  1.5715027e-02],
       [ 2.6405776e-01,  1.5715027e-02],
       [ 0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00],
       [ 0.00000

In [7]:
data.loc[0,'TRAJS_CTRS'].shape


(14, 2)

In [8]:
data.loc[0,'TRAJS_VECS'].shape


(14, 2)

In [13]:
data.loc[0,'PAD_FLAGS']


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [10]:
data.loc[0,'LANE_GRAPH'].keys()


dict_keys(['node_ctrs', 'node_vecs', 'turn', 'control', 'intersect', 'left', 'right', 'lane_ctrs', 'lane_vecs', 'num_nodes', 'num_lanes', 'rel_lane_flags'])

In [8]:
import pandas as pd

df = pd.DataFrame({'math':[90,80,70], 'chinese':[85, 90, 87]})
print(df.values)
df['math'].values
print(df.loc[:,'math'])
print(df['math'])
print(df['math'].values)


[[90 85]
 [80 90]
 [70 87]]
0    90
1    80
2    70
Name: math, dtype: int64
0    90
1    80
2    70
Name: math, dtype: int64
[90 80 70]


In [12]:
import torch
torch.arange(24).view(2,3,4)[:1,:]

/home/wangchen/.conda/envs/simpl/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])